server:
  port: 8083
spring:
  application:
    name: vets-service
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://mysql:3306/petclinic?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    cache-names: vets
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework: INFO
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
vets:
  cache:
    ttl: 60
    heap-size: 100

        
  