server:
  port: 9090
    
---
spring:
  profiles: docker
  boot:
    admin:
      url: http://${ADMIN_SERVER_SERVICE_HOST}:${ADMIN_SERVER_SERVICE_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/