vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db-service:3306/petclinic?createDatabaseIfNotExist=true&useSSL=false
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/