server:
  port: 8989
turbine:
  app-config: visits-service,customers-service,vets-service
  cluster-name-expression: new String("default")
spring:
  application:
    name: turbine-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework: INFO
