server:
  port: 8761

spring:
  application:
    name: discovery-service
eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost
    preferIpAddress: true
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

