spring:
  application:
    name: api-gateway-service
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway-service: /gateway/**

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework: INFO

spring.messages.basename: messages/messages